### ISSUE TITLE
pre-commit autoupdate pr

### ISSUE THREAD

**Issue by afuetterer** [afuetterer/rdmo#25]
```yaml
name: Scheduled update of pre-commit hooks

permissions:
  contents: read

on:
  schedule:
    # run once a month at midnight of the first day of the month
    - cron: 0 0 1 * *
  # run manually from actions tab
  # https://github.com/afuetterer/rdmo/actions/workflows/pytest.yml
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
      - run: pip install pre-commit
      - run: pre-commit autoupdate

     # test if file changed

      - uses: actions/upload-artifact@v3
        with:
          name: .pre-commit-config.yaml
          path: .pre-commit-config.yaml
          retention-days: 1

  create-pr:
    needs: [update]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Download .pre-commit-config.yaml
        uses: actions/download-artifact@v3
        with:
          name: .pre-commit-config.yaml

      # https://github.com/peter-evans/create-pull-request
      # https://github.com/peter-evans/create-pull-request/issues/48
      - uses: peter-evans/create-pull-request@v5
        with:
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          base: main
          branch: pre-commit-autoupdate
          title: "chore(deps-dev): update pre-commit hooks"
          commit-message: "chore(deps-dev): update pre-commit hooks"
          body: |
            Update pre-commit hooks

            This PR is auto-generated once a month at midnight of the first day of the month.
          labels: |
            dependencies
            pre-commit
            type: maintainance
          delete-branch: true
```
